### ISSUE TITLE
No way to control page PADDING

### ISSUE THREAD

**Issue by nircelero** [idrsolutions/idrviewer#4]
Hey there! 
Thanks for implementing this awesome PDF viewer.

We would love to be able to control the PADDING attribute from the config property. 

Any chance you could add it?

Thanks!

**Comment by leonatherton** [comment]
Hi, I will review this next week and get back to you. Thanks

**Comment by leonatherton** [comment]
This has been added in the next release. Unfortunately we just missed yesterday's release so it will go live in the next one on Nov 15.

**Comment by nircelero** [comment]
Thanks!

**Comment by nircelero** [comment]
Actually @leonatherton, would it be possible to control both vertical padding and horizontal padding? We have 2 use cases:
1. Having no padding at all.
2. Having a fixed padding on ZOOM_FITWIDTH.

I know it's a bigger change, but it would be really helpful!

**Comment by nircelero** [comment]
Actually @leonatherton it would be really nice to control both the vertical padding (i.e. padding-top and padding-bottom) as well as the horizontal padding (i.e. padding-left and padding-right). We have two use cases we would like to support:
1. Having no padding at all.
2. Having fixed padding together with ZOOM_FITWIDTH, so it looks like a document but stretched to the maximum width.

I know it is a little more effort, but could be really helpful!

**Comment by nircelero** [comment]
@leonatherton you can check out this fork as an example:
https://github.com/Celero-io/idrviewer-fork

**Comment by leonatherton** [comment]
@nircelero Thank you for providing the example. We've put this feature live in [today's release](https://github.com/idrsolutions/idrviewer/commit/45d13e0f1a6c0495265696f3e970d7c7c5308863#diff-aa806308120c3a1e82406ceab8c31e23b0c86980c7042bab6a13da0dce74c046).

We've gone with paddingX and paddingY as the config property names. Note also that the expected value is slightly different. E.g. If you provide paddingX=5, then it will set 5 on the left and 5 on the right for a combined total of 10.
